### ISSUE TITLE
Error: Requested format Bgra8UnormSrgb is not in list of supported formats

### ISSUE THREAD

**Issue by d3cryptofc** [Kirottu/watershot#23]
It looks like both `watershot` and `watershot-git` are crashing here on Hyprland :(
```
$ yay -Ss watershot
aur/watershot-git r51.0874e09-1 (+0 0.00) (Installed: r41.1f7c9e6-1)
    A simple wayland native screenshot tool.
```

**Version**
```
$ watershot --version
watershot 0.2.1
```

**Backtrace**
```
$ RUST_BACKTRACE=full watershot

thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Requested format Bgra8UnormSrgb is not in list of supported formats: [Bgra8Unorm]
', /home/lelzin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:771:18
stack backtrace:
   0:     0x55c0ff43d061 - <unknown>
   1:     0x55c0ff46552e - <unknown>
   2:     0x55c0ff43a461 - <unknown>
   3:     0x55c0ff43ce75 - <unknown>
   4:     0x55c0ff43e3d7 - <unknown>
   5:     0x55c0ff43e15a - <unknown>
   6:     0x55c0ff43e8d8 - <unknown>
   7:     0x55c0ff43e7d7 - <unknown>
   8:     0x55c0ff43d496 - <unknown>
   9:     0x55c0ff43e4d2 - <unknown>
  10:     0x55c0fee51f13 - <unknown>
  11:     0x55c0fef78bdd - <unknown>
  12:     0x55c0fef7a5eb - <unknown>
  13:     0x55c0fef87e83 - <unknown>
  14:     0x55c0fef3dc09 - <unknown>
  15:     0x55c0fee642a0 - <unknown>
  16:     0x55c0fee9c1ad - <unknown>
  17:     0x55c0feeb7f25 - <unknown>
  18:     0x55c0feeb8b24 - <unknown>
  19:     0x55c0feeb8d2f - <unknown>
  20:     0x55c0feeb926e - <unknown>
  21:     0x55c0feee56f4 - <unknown>
  22:     0x55c0feec9ad3 - <unknown>
  23:     0x55c0feea7859 - <unknown>
  24:     0x55c0ff4337a2 - <unknown>
  25:     0x55c0feee7185 - <unknown>
  26:     0x7f8bbda27cd0 - <unknown>
  27:     0x7f8bbda27d8a - __libc_start_main
  28:     0x55c0fee526b5 - <unknown>
  29:                0x0 - <unknown>
```

**Comment by Kirottu** [comment]
Seems like my naive solution of just hard coding the format in finally failed me, I'll need to rework it into using an actually supported format.

**Comment by Andy3153** [comment]
Same thing happens to me too.

**Comment by Kirottu** [comment]
Yeah... I haven't had time to work on it yet unfortunately. I have a lot going on right now so a fix will likely take time.

**Comment by anufrievroman** [comment]
I have this error on a laptop with Nvidia card, but on another more normal PC it's fine. Both have Hyprland, so I don't know if WM is the issue...

**Comment by offeex** [comment]
same here. I have nvidia, but using hybrid graphics (primarily amd cpu)

**Comment by Kirottu** [comment]
Alright, I have finally had a stab at this issue and a possible fix is available in the `surface-format-fix` branch. Can someone test it to see if it actually fixes the issue?

**Comment by beh-10257** [comment]
```
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost
', /home/behe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.0/src/backend/direct.rs:771:18
stack backtrace:
   0:     0x55d7d5151611 - std::backtrace_rs::backtrace::libunwind::trace::hf5c7281d89c111e3
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d7d5151611 - std::backtrace_rs::backtrace::trace_unsynchronized::hb866754e122ebfe9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d7d5151611 - std::sys_common::backtrace::_print_fmt::hdfaa11a49a832af0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55d7d5151611 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5620211fe7cc0c26
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d7d517ebbf - core::fmt::rt::Argument::fmt::h6bd55fd29ab26043
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x55d7d517ebbf - core::fmt::write::h465f4055b131d5b2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0x55d7d514e239 - std::io::Write::write_fmt::h71f0fb622ab3ef3f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0x55d7d5151425 - std::sys_common::backtrace::_print::h445f39dc21058a32
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55d7d5151425 - std::sys_common::backtrace::print::h9590ee5cbddc6df4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55d7d5152953 - std::panicking::default_hook::{{closure}}::ha16ca76146c72a73
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0x55d7d51526e4 - std::panicking::default_hook::hb767f21a86ebb9e4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
  11:     0x55d7d5152ed9 - std::panicking::rust_panic_with_hook::hc1bbb079611b71b1
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:705:13
  12:     0x55d7d5152dd7 - std::panicking::begin_panic_handler::{{closure}}::hb36c7246dcdcc8ce
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:597:13
  13:     0x55d7d5151a76 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c2f223e3134d49e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55d7d5152b22 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  15:     0x55d7d4b182e3 - core::panicking::panic_fmt::h2246a13f2021f0df
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
  16:     0x55d7d4c47c0c - wgpu::backend::direct::Context::handle_error_fatal::h8422957dada885df
  17:     0x55d7d4c49bab - <wgpu::backend::direct::Context as wgpu::context::Context>::surface_configure::h94b1521c237a61f6
  18:     0x55d7d4c577c3 - <T as wgpu::context::DynContext>::surface_configure::hf8fd16eb02d86010
  19:     0x55d7d4bfa5c1 - wgpu::Surface::configure::h7412f10448f2cb87
  20:     0x55d7d4b412e4 - watershot::sctk_impls::layer_shell_handler::<impl smithay_client_toolkit::shell::wlr_layer::LayerShellHandler for watershot::runtime_data::RuntimeData>::configure::haa47a68fbb7db1fe
  21:     0x55d7d4b7be2f - smithay_client_toolkit::shell::wlr_layer::dispatch::<impl wayland_client::event_queue::Dispatch<wayland_protocols_wlr::layer_shell::v1::generated::client::zwlr_layer_surface_v1::ZwlrLayerSurfaceV1,smithay_client_toolkit::shell::wlr_layer::LayerSurfaceData,D> for smithay_client_toolkit::shell::wlr_layer::LayerShell>::event::h5ac29e22f7a85ed0
  22:     0x55d7d4b8ce99 - wayland_client::event_queue::queue_callback::hae9f15b7c0c73d3f
  23:     0x55d7d4b8d524 - wayland_client::event_queue::EventQueue<State>::dispatching_impl::hb3e21186c9b152dd
  24:     0x55d7d4b8d79f - wayland_client::event_queue::EventQueue<State>::blocking_dispatch::h2204f964172d9963
  25:     0x55d7d4b8dcce - wayland_client::event_queue::EventQueue<State>::roundtrip::ha5627d56993cde3c
  26:     0x55d7d4b70fe4 - watershot::main::h731d862f435b1855
  27:     0x55d7d4b2e453 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcba615a8264913d1
  28:     0x55d7d4b5cff9 - std::rt::lang_start::{{closure}}::hf4dc772864ff6f8f
  29:     0x55d7d514776b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h170ba8d2f555cb36
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:284:13
  30:     0x55d7d514776b - std::panicking::try::do_call::h5c310c7c8955fc01
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  31:     0x55d7d514776b - std::panicking::try::h30fa2e7d64ca1615
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  32:     0x55d7d514776b - std::panic::catch_unwind::h432c11e19dc54d82
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  33:     0x55d7d514776b - std::rt::lang_start_internal::{{closure}}::hc73e5e4182e8d8fb
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/rt.rs:148:48
  34:     0x55d7d514776b - std::panicking::try::do_call::hc309fdded4892d10
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  35:     0x55d7d514776b - std::panicking::try::h9ea1af60a56b6bdf
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  36:     0x55d7d514776b - std::panic::catch_unwind::h6cb2a38063af28f3
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  37:     0x55d7d514776b - std::rt::lang_start_internal::hf2855a9c5fc65604
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/rt.rs:148:20
  38:     0x55d7d4b73155 - main
  39:     0x7f8500827cd0 - <unknown>
  40:     0x7f8500827d8a - __libc_start_main
  41:     0x55d7d4b18a45 - _start
  42:                0x0 - <unknown>
```

**Comment by beh-10257** [comment]
yeah it didn't work and that's a new backtrace I guess

**Comment by Kirottu** [comment]
It seems like that error is a [known `wgpu` issue for Nvidia and Wayland](https://github.com/gfx-rs/wgpu/issues/2519) from an initial search of that error. I have no idea what to do about it though at this point.

**Comment by uttarayan21** [comment]
Hi, on my system with Hyprland, nvidia gpu and dual monitors ( one using bgr and one using rgb subpixels ) the `surface-format-fix` branch does seem to fix the issue.

First picture is the screenshot of the watershot selector ( taken with grim / slurp ? ) 
![20230925_02h46m18s_grim](https://github.com/Kirottu/watershot/assets/18732700/23b592fd-5e95-49a4-af6a-782fe27992d0)
This is the actual screenshot taken using watershot
![output](https://github.com/Kirottu/watershot/assets/18732700/6f2db1c8-2431-4de3-95f6-1002767b9493)

**Comment by Kirottu** [comment]
Ok well at least it does the trick for some people, I shall make a new release soon enough.

**Comment by Kirottu** [comment]
Closing this issue now as this specific problem is fixed, feel free to create a new issue for the `Device is lost` @beh-10257.
