### ISSUE TITLE
`wgpu` panics on a vmware VM

### ISSUE THREAD

**Issue by tranzystorekk** [Kirottu/watershot#27]
Panic message:

```
[ERROR wgpu::backend::direct] Error in Adapter::request_device: Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RequestDeviceError', src/runtime_data.rs:126:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Environment:

Void Linux
Vmware Workstation Player VM Guest
Compositor: labwc 0.6.4 (wlroots)
watershot 0.2.1, built as a Void Linux package

**Comment by Kirottu** [comment]
It seems like the VMWare GPU drivers have some problems with wgpu, so I would look into other issues similar to this and if other projects using wgpu work first.

**Comment by tranzystorek-io** [comment]
FWIW I use https://github.com/raphamorim/rio on this same vmware system without similar problems.

Not sure if this is caused by some more direct interaction with wayland/labwc/etc.

**Comment by tranzystorek-io** [comment]
Did some tinkering around, the immediate issue can be solved by using `wgpu::Limits::downlevel_webgl2_defaults()`, but even then the texture format capabilities still cause webgl to crash

**Comment by Kirottu** [comment]
Yeah the texture format capabilities is a known issue and I haven't gotten around to fixing it as it needs major refactoring across the whole codebase.

**Comment by tranzystorek-io** [comment]
No sweat, thank you for looking at this issue anyway 😄

**Comment by Kirottu** [comment]
Alright I finally decided to have a stab at the long standing issue, I pushed a possible fix to the surface format issue to the branch `surface-format-fix`. Would you mind giving it a try to see if it works?

**Comment by tranzystorek-io** [comment]
Unfortunately still:

```
~
❯ RUST_BACKTRACE=1 watershot
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadDisplay', /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.0/src/gles/eg
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: wgpu_hal::gles::egl::AdapterContext::lock
   4: wgpu_hal::gles::adapter::<impl wgpu_hal::Adapter<wgpu_hal::gles::Api> for wgpu_hal::gles::Adapter>::texture_format_capabilities
   5: wgpu_core::device::resource::Device<A>::describe_format_features
   6: wgpu_core::device::resource::Device<A>::create_render_pipeline
   7: wgpu_core::device::global::<impl wgpu_core::global::Global<G>>::device_create_render_pipeline
   8: <wgpu::backend::direct::Context as wgpu::context::Context>::device_create_render_pipeline
   9: <T as wgpu::context::DynContext>::device_create_render_pipeline
  10: wgpu::Device::create_render_pipeline
  11: watershot::rendering::Renderer::new
  12: watershot::sctk_impls::layer_shell_handler::<impl smithay_client_toolkit::shell::wlr_layer::LayerShellHandler for watershot::runtime_data::RuntimeData>::configure
  13: smithay_client_toolkit::shell::wlr_layer::dispatch::<impl wayland_client::event_queue::Dispatch<wayland_protocols_wlr::layer_shell::v1::generated::client::zwlr_laye
  14: wayland_client::event_queue::queue_callback
  15: wayland_client::event_queue::EventQueue<State>::dispatching_impl
  16: wayland_client::event_queue::EventQueue<State>::blocking_dispatch
  17: wayland_client::event_queue::EventQueue<State>::roundtrip
  18: watershot::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadDisplay', /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.0/src/gles/eg
stack backtrace:
   0:     0x55b8485d4b31 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h415229f7b2fca78e
   1:     0x55b84860128e - core::fmt::write::h28fb50bb262ea1b4
   2:     0x55b8485d1917 - std::io::Write::write_fmt::hffbb0afe6e8b0d78
   3:     0x55b8485d4945 - std::sys_common::backtrace::print::hce0a8e46d986e642
   4:     0x55b8485d5f34 - std::panicking::default_hook::{{closure}}::h155069ddad794f9c
   5:     0x55b8485d5c5a - std::panicking::default_hook::h8bc760cc0648492d
   6:     0x55b8485d64e5 - std::panicking::rust_panic_with_hook::ha439e181de84b322
   7:     0x55b8485d63e7 - std::panicking::begin_panic_handler::{{closure}}::h9e7cd98d71ee1ac4
   8:     0x55b8485d4f96 - std::sys_common::backtrace::__rust_end_short_backtrace::hdfd0b3c653f57627
   9:     0x55b8485d60f2 - rust_begin_unwind
  10:     0x55b847fd5503 - core::panicking::panic_fmt::he92bf07b4379581c
  11:     0x55b847fd59a3 - core::result::unwrap_failed::hbdea9ce01a999e23
  12:     0x55b84828f27e - wgpu_hal::gles::egl::AdapterContext::lock::he6a6be63db27b248
  13:     0x55b84825b5ef - wgpu_hal::gles::device::<impl wgpu_hal::Device<wgpu_hal::gles::Api> for wgpu_hal::gles::Device>::destroy_buffer::hd591575002daf2a7
  14:     0x55b8481fb0d2 - wgpu_core::device::resource::Device<A>::dispose::h818bf424d5f9f85c
  15:     0x55b848138b2d - wgpu_core::hub::Hub<A,F>::clear::h3422ea8812f1fe9f
  16:     0x55b848181d7c - <wgpu_core::global::Global<G> as core::ops::drop::Drop>::drop::hf77f8ec1809c31fd
  17:     0x55b8480ac771 - core::ptr::drop_in_place<wgpu_core::global::Global<wgpu_core::identity::IdentityManagerFactory>>::hbe597ac7b17c33dc
  18:     0x55b84804c3fd - alloc::sync::Arc<T>::drop_slow::h77a0f6e569e2f0fb
  19:     0x55b84802e8e9 - core::ptr::drop_in_place<wgpu::Queue>::h974c62d6957120de
  20:     0x55b848034dc6 - watershot::main::h0fb50c67341589d9
  21:     0x55b84802e2c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he8d2bbc9d7c6c96d
  22:     0x55b847fe5af9 - std::rt::lang_start::{{closure}}::h49bdb426817152ac
  23:     0x55b8485cac78 - std::rt::lang_start_internal::h71fb5f7e4d3d800b
  24:     0x55b8480350e5 - main
  25:     0x7f4e77a0320c - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  26:     0x7f4e77a032bc - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  27:     0x55b847fd5c61 - _start
                               at ./csu/../sysdeps/x86_64/start.S:115
  28:                0x0 - <unknown>
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x55b8485d4b31 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h415229f7b2fca78e
   1:     0x55b84860128e - core::fmt::write::h28fb50bb262ea1b4
   2:     0x55b8485d1917 - std::io::Write::write_fmt::hffbb0afe6e8b0d78
   3:     0x55b8485d4945 - std::sys_common::backtrace::print::hce0a8e46d986e642
   4:     0x55b8485d5f34 - std::panicking::default_hook::{{closure}}::h155069ddad794f9c
   5:     0x55b8485d5c5a - std::panicking::default_hook::h8bc760cc0648492d
   6:     0x55b8485d64e5 - std::panicking::rust_panic_with_hook::ha439e181de84b322
   7:     0x55b8485d63a1 - std::panicking::begin_panic_handler::{{closure}}::h9e7cd98d71ee1ac4
   8:     0x55b8485d4f96 - std::sys_common::backtrace::__rust_end_short_backtrace::hdfd0b3c653f57627
   9:     0x55b8485d60f2 - rust_begin_unwind
  10:     0x55b847fd5543 - core::panicking::panic_nounwind_fmt::h893c795ad41bb807
  11:     0x55b847fd55e7 - core::panicking::panic_nounwind::h5f5043ad3388f8c2
  12:     0x55b847fd5683 - core::panicking::panic_cannot_unwind::h9ee22ab8316c642b
  13:     0x55b848034ee9 - watershot::main::h0fb50c67341589d9
  14:     0x55b84802e2c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he8d2bbc9d7c6c96d
  15:     0x55b847fe5af9 - std::rt::lang_start::{{closure}}::h49bdb426817152ac
  16:     0x55b8485cac78 - std::rt::lang_start_internal::h71fb5f7e4d3d800b
  17:     0x55b8480350e5 - main
  18:     0x7f4e77a0320c - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  19:     0x7f4e77a032bc - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  20:     0x55b847fd5c61 - _start
                               at ./csu/../sysdeps/x86_64/start.S:115
  21:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
zsh: IOT instruction  RUST_BACKTRACE=1 watershot
```

**Comment by Kirottu** [comment]
Ok well that is a different error from the surface error... and it would seem like the panic itself originates from non-Watershot code so I do not know what is going on with that code.

**Comment by SirWrexes** [comment]
Same issue (only with a less explicit trace) on Arch (6.5.3-arch1-1) with Hyprland:
```
~
❯ RUST_BACKTRACE=1 watershot
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadDisplay', /home/wrexes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.0/src/gles/egl.rs:351:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadDisplay', /home/wrexes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.0/src/gles/egl.rs:351:14
stack backtrace:
   0:     0x555cdfcdb381 - <unknown>
   1:     0x555cdfd084df - <unknown>
   2:     0x555cdfcd7fa9 - <unknown>
   3:     0x555cdfcdb195 - <unknown>
   4:     0x555cdfcdc6c3 - <unknown>
   5:     0x555cdfcdc454 - <unknown>
   6:     0x555cdfcdcc49 - <unknown>
   7:     0x555cdfcdcb47 - <unknown>
   8:     0x555cdfcdb7e6 - <unknown>
   9:     0x555cdfcdc892 - <unknown>
  10:     0x555cdf6df8e3 - <unknown>
  11:     0x555cdf6dfd83 - <unknown>
  12:     0x555cdf99467f - <unknown>
  13:     0x555cdf961a54 - <unknown>
  14:     0x555cdf83bf21 - <unknown>
  15:     0x555cdf88a16d - <unknown>
  16:     0x555cdf7b50d1 - <unknown>
  17:     0x555cdf754503 - <unknown>
  18:     0x555cdf738b2f - <unknown>
  19:     0x555cdf73e01f - <unknown>
  20:     0x555cdf73f463 - <unknown>
  21:     0x555cdf6efe49 - <unknown>
  22:     0x555cdfcd14db - <unknown>
  23:     0x555cdf73e335 - <unknown>
  24:     0x7f6095a27cd0 - <unknown>
  25:     0x7f6095a27d8a - __libc_start_main
  26:     0x555cdf6e0045 - <unknown>
  27:                0x0 - <unknown>
thread 'main' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x555cdfcdb381 - <unknown>
   1:     0x555cdfd084df - <unknown>
   2:     0x555cdfcd7fa9 - <unknown>
   3:     0x555cdfcdb195 - <unknown>
   4:     0x555cdfcdc6c3 - <unknown>
   5:     0x555cdfcdc454 - <unknown>
   6:     0x555cdfcdcc49 - <unknown>
   7:     0x555cdfcdcb01 - <unknown>
   8:     0x555cdfcdb7e6 - <unknown>
   9:     0x555cdfcdc892 - <unknown>
  10:     0x555cdf6df923 - <unknown>
  11:     0x555cdf6df9c7 - <unknown>
  12:     0x555cdf6dfa63 - <unknown>
  13:     0x555cdf73e139 - <unknown>
  14:     0x555cdf73f463 - <unknown>
  15:     0x555cdf6efe49 - <unknown>
  16:     0x555cdfcd14db - <unknown>
  17:     0x555cdf73e335 - <unknown>
  18:     0x7f6095a27cd0 - <unknown>
  19:     0x7f6095a27d8a - __libc_start_main
  20:     0x555cdf6e0045 - <unknown>
  21:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
fish: Job 1, 'RUST_BACKTRACE=1 watershot' terminated by signal SIGABRT (Abort)
```
