### ISSUE TITLE
Panic in RuntimeData

### ISSUE THREAD

**Issue by Lord-Valen** [Kirottu/watershot#32]
While testing https://github.com/NixOS/nixpkgs/pull/259299, I've been getting [```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/runtime_data.rs:116:14```](https://github.com/Kirottu/watershot/blob/64a97b995b153e48063b1cdfda39c9b67f08fe93/src/runtime_data.rs#L116). It's odd because nothing seems to have touched that file between 0.2.0 and 0.2.2 though there have been updated dependencies. I'm testing with grim 1.4.1 and Hyprland 0.30.0.

**Comment by Schweber** [comment]
I experience the same, also on NixOS and Hyprland. Here is the backtrace:

```
 ~  RUST_BACKTRACE=full watershot                                                                                                                   ✘ 101
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/runtime_data.rs:100:14
stack backtrace:
   0:     0x55f593d24290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf014552b94f53b0b
   1:     0x55f593d4d7ff - core::fmt::write::hd931ce1f65786f99
   2:     0x55f593d1cc27 - std::io::Write::write_fmt::h6a6fd63a04e82ec7
   3:     0x55f593d24095 - std::sys_common::backtrace::print::h1e42468794e7b82c
   4:     0x55f593d0a891 - std::panicking::default_hook::{{closure}}::hbe45423b43205803
   5:     0x55f593d0a52f - std::panicking::default_hook::h84640917dec96f40
   6:     0x55f593d0ad39 - std::panicking::rust_panic_with_hook::h3f828bf7de94854a
   7:     0x55f593d24531 - std::panicking::begin_panic_handler::{{closure}}::h1494d1b7b833ecd5
   8:     0x55f593d24366 - std::sys_common::backtrace::__rust_end_short_backtrace::hfb56cb4321fb1fc8
   9:     0x55f593d0aa62 - rust_begin_unwind
  10:     0x55f593671783 - core::panicking::panic_fmt::h69ad0a157a771ebb
  11:     0x55f593671813 - core::panicking::panic::h49ef28648bcd6145
  12:     0x55f5936afc57 - watershot::runtime_data::RuntimeData::new::h4b41eb129d82f87e
  13:     0x55f59374f82d - watershot::main::h0c8cc5907004a3ba
  14:     0x55f5936827d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hde49ba551786c1f6
  15:     0x55f5936827e9 - std::rt::lang_start::{{closure}}::h2c3d7e288f6e8a4b
  16:     0x55f593d01017 - std::rt::lang_start_internal::hbcbc84fca12d560d
  17:     0x55f5937514a5 - main
  18:     0x7f3be9f2dace - __libc_start_call_main
  19:     0x7f3be9f2db89 - __libc_start_main@@GLIBC_2.34
  20:     0x55f593671e55 - _start
  21:                0x0 - <unknown>
```

**Comment by nyabinary** [comment]
any way to solve this?

**Comment by jasper-at-windswept** [comment]
Sorry to make a unhelpful comment but I am having this same issue.
NixOS: 24.05
Package Version: 0.2.0
Installed with Nixpkgs
