### ISSUE TITLE
Failed to parse grim image!: IoError - failed to fill whole buffer

### ISSUE THREAD

**Issue by Akiyamka** [Kirottu/watershot#34]
```sh
$  RUST_BACKTRACE=1 watershot

thread 'main' panicked at 'Failed to parse grim image!: IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', src/runtime_data.rs:75:14
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: watershot::runtime_data::RuntimeData::new
   4: watershot::main
```
Env:
```
watershot 0.2.0
```

**Comment by janickm** [comment]
Same with 

watershot `main` (`1722590`)
grim 1.4.0+ds-2build2
ubuntu24.04 with gnome

**Comment by vvzen** [comment]
Same here on Cosmic (PopOS 24.04 LTS) :
```bash
$ git log --oneline | head -n 1
64a97b9 Updated Cargo.lock

$ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/watershot`

thread 'main' panicked at src/runtime_data.rs:91:14:
Failed to parse grim image!: IoError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/result.rs:1732:5
   3: core::result::Result<T,E>::expect
             at /home/vv/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1089:23
   4: watershot::runtime_data::RuntimeData::new
             at ./src/runtime_data.rs:89:21
   5: watershot::gui
             at ./src/main.rs:105:28
   6: watershot::main
             at ./src/main.rs:36:26
   7: core::ops::function::FnOnce::call_once
             at /home/vv/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
```

**Comment by Akiyamka** [comment]
@vvzen project is kinda dead

**Comment by Kirottu** [comment]
I unfortunately have quite a bit on my plate right now and since I don't use Watershot as my screenshot tool anymore, it has taken a backburner position. That being said, I'll try to look into what is going on with this problem but can't promise much.
