### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by nonetrix** [Kirottu/watershot#38]
Tried to run on NixOS using Hyprland but just got this 
```
thread 'main' panicked at src/runtime_data.rs:100:14:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Running with `RUST_BACKTRACE=1` it returns
```
thread 'main' panicked at src/runtime_data.rs:100:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: watershot::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Finally running with `RUST_BACKTRACE=full` returns:
```
thread 'main' panicked at src/runtime_data.rs:100:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x55eb1b9a2afb - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h85e32f8f7b08f729
   1:     0x55eb1b9dae30 - core::fmt::write::hae1cf5cde4ee2188
   2:     0x55eb1b997eb5 - std::io::Write::write_fmt::h4ae54bff47727b29
   3:     0x55eb1b9a28d4 - std::sys_common::backtrace::print::hea248a594c5888cf
   4:     0x55eb1b9a3527 - std::panicking::default_hook::{{closure}}::h545cae1ad29f25d2
   5:     0x55eb1b9a3274 - std::panicking::default_hook::hc1d7fee5faf0cc8a
   6:     0x55eb1b9a3a88 - std::panicking::rust_panic_with_hook::h0e7975574d129b7c
   7:     0x55eb1b9a3939 - std::panicking::begin_panic_handler::{{closure}}::h420dcc10a77211ab
   8:     0x55eb1b9a2d16 - std::sys_common::backtrace::__rust_end_short_backtrace::he6597460302ecd4a
   9:     0x55eb1b9a36d2 - rust_begin_unwind
  10:     0x55eb1b339015 - core::panicking::panic_fmt::h3cf3338e18ada46e
  11:     0x55eb1b3390b3 - core::panicking::panic::h751818a9309dd3b6
  12:     0x55eb1b3bae18 - watershot::main::h468dfd819eb9a670
  13:     0x55eb1b398233 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21e3cb98c11d1d5c
  14:     0x55eb1b43b6e9 - std::rt::lang_start::{{closure}}::h8f1e8f8b046154c0
  15:     0x55eb1b9a35c4 - std::panicking::try::h839c5e98485eaaba
  16:     0x55eb1b9ad69b - std::rt::lang_start_internal::h6a4b333c7c2ab7bd
  17:     0x55eb1b43b6de - std::rt::lang_start::h079530eb5d11fcaa
  18:     0x7f46bf74f0ce - __libc_start_call_main
  19:     0x7f46bf74f189 - __libc_start_main@GLIBC_2.2.5
  20:     0x55eb1b339785 - _start
  21:                0x0 - <unknown>
```

**Comment by mobsenpai** [comment]
+1

**Comment by IronRevelation** [comment]
+1

**Comment by 39555** [comment]
+1

**Comment by KMohZaid** [comment]
+!, i am using nixos

**Comment by aelloc** [comment]
<img width="200" alt="Image" src="https://github.com/user-attachments/assets/45405240-3246-4a75-aa98-68a881058ced" />

**Comment by nonetrix** [comment]
I do think I titled the issue vaguely to be funny
